name: actions-unittest
on: [push]
jobs:
  unittest:
    runs-on: ubuntu-latest
    container: node:12
    services:
      redis:
        image: redis:latest
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ""
    steps:
      - uses: actions/checkout@v2
      - run: npm install -g lerna
      - run: lerna bootstrap
      - run: cp -r src/front/_config src/front/config
      - run: cp -r src/backend/_config src/backend/config
      - run: npm run test:backend
