name: actions-unittest
on: [push]
jobs:
  unittest:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
      mysql:
        image: mysql:latest
        ports:
          - 33060:3306
        env:
          MYSQL_ROOT_PASSWORD: ""
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm install -g lerna
      - run: lerna bootstrap
      - run: cp -r src/front/_config src/front/config
      - run: cp -r src/backend/_config src/backend/config
      - run: npm run test:backend
